# Site settings
title: Mingjie's page
SEOTitle: Mingjie's Page
header-img: img/home-bg.jpg
email: ssaajianmigjie@gmail.com
description: "ひびけ"
keyword: ""
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:
zhihu_username:     jian-ming-jie
github_username:    mingjieJian
#twitter_username:
#facebook_username:

research_note: true
research_note_url: https://mk-cookbook.readthedocs.io/en/latest/

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: mingjiejian-github-io

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-DCJ7NPZE95'            # Format: UA-xxxxxx-xx
ga_domain: mingjiejian.github.io

# Google Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : 'G-DCJ7NPZE95'
    anonymize_ip         : false


# Sidebar settings
sidebar: true                         # whether or not using Sidebar.
sidebar-about-description: "Researcher and gamer"
sidebar-avatar: /img/profile_small.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
mathjax-single-dollar: true

# Friends
friends: [
    {
        title: "Gerry",
        href: "http://gerry.lamost.org/blog/"
    },{
        title: "Fmajor's Blog",
        href: "http://fmajor.lamost.org/blog/"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
]

# RSS feed
name:         Mingjie's Blog
description:  Write everything, think everything.
url:          https://mingjiejian.github.io/